// GENERATED by tools/assets/packbank.py (tools/mkcard.py runs it). Do not edit:
// re-run it.
//
// The sprite bank on the card (section BANK of CRITTERS.DAT): where each clip
// (one animation of a sheet) is and how to play it. A frame on the card is an
// 8 B header {wWords, h, ox, oy, csum8, flags, w, 0} and h rows of wWords words
// (gfx_blit4k's format, 15 transparent); ox, oy put its top-left relative to
// the actor's position (the sheet's pivot, the middle of the feet line). A
// clip's stored frames sit bankPerBlock() to a block at multiples of its slot
// (slot4 * 4 bytes), from block `first` of the section; BANK_FMAP maps a played
// frame to a stored one when the clip repeats frames (map != BANK_NO_MAP).
#pragma once
#include <stdint.h>

struct BankClip {
    uint16_t first;     // first block, counted from the section's start
    uint8_t frames;     // as played
    uint8_t slot4;      // bytes a frame takes in its block (its biggest frame) / 4
    uint8_t msPer10;    // frame time / 10 ms
    uint8_t map;        // offset in BANK_FMAP, or BANK_NO_MAP (frame f is stored f)
    uint8_t stored;     // distinct frames on the card
    uint8_t active;     // attack: first << 4 | last hurting frame; 0 none
    uint16_t sizes;     // offset in BANK_FSIZE of its stored frames' sizes
};

constexpr uint8_t BANK_NO_MAP = 0xFF;
constexpr uint16_t BANK_BLOCKS = 100;      // the section, 188 stored frames
constexpr uint8_t BANK_FRAME_HEADER = 8;
constexpr uint16_t BANK_MAX_SLOT = 488;

enum : uint8_t {
    CLIP_SQUIRE_IDLE                   =  0,   //  4 frames, 4 stored, 2 a block (176 B)
    CLIP_SQUIRE_WALK                   =  1,   //  8 frames, 8 stored, 2 a block (236 B)
    CLIP_SQUIRE_THRUST                 =  2,   //  7 frames, 7 stored, 1 a block (344 B)
    CLIP_SQUIRE_PARRY                  =  3,   //  6 frames, 6 stored, 1 a block (260 B)
    CLIP_SQUIRE_DAMAGE                 =  4,   //  4 frames, 4 stored, 2 a block (248 B)
    CLIP_SQUIRE_DEATH                  =  5,   //  5 frames, 5 stored, 2 a block (248 B)
    CLIP_RACCOON_IDLE                  =  6,   //  8 frames, 6 stored, 3 a block (152 B)
    CLIP_RACCOON_RUN                   =  7,   //  8 frames, 8 stored, 3 a block (164 B)
    CLIP_RACCOON_ATTACK                =  8,   //  4 frames, 4 stored, 2 a block (176 B)
    CLIP_RACCOON_DEATH                 =  9,   //  4 frames, 3 stored, 3 a block (152 B)
    CLIP_TURTLE_IDLE_YAWN              = 10,   // 12 frames, 6 stored, 2 a block (176 B)
    CLIP_TURTLE_IDLE_BLINK             = 11,   // 10 frames, 5 stored, 3 a block (152 B)
    CLIP_TURTLE_WALK                   = 12,   //  4 frames, 3 stored, 3 a block (152 B)
    CLIP_TURTLE_SLEEP                  = 13,   //  6 frames, 4 stored, 3 a block (168 B)
    CLIP_TURTLE_BITE                   = 14,   //  5 frames, 5 stored, 2 a block (176 B)
    CLIP_TURTLE_SHELL                  = 15,   // 10 frames, 9 stored, 3 a block (152 B)
    CLIP_BEAVER_IDLE                   = 16,   //  4 frames, 4 stored, 4 a block (128 B)
    CLIP_BEAVER_MOVEMENT               = 17,   //  4 frames, 4 stored, 4 a block (128 B)
    CLIP_BEAVER_MOVEMENT_WITH_STICK    = 18,   //  4 frames, 4 stored, 3 a block (168 B)
    CLIP_BEAVER_BITE                   = 19,   //  4 frames, 4 stored, 4 a block (128 B)
    CLIP_BEAVER_DAMAGE                 = 20,   //  4 frames, 4 stored, 3 a block (140 B)
    CLIP_BEAVER_DEATH                  = 21,   //  2 frames, 2 stored, 1 a block (456 B)
    CLIP_BEAVER_IDLE_WATER             = 22,   //  4 frames, 4 stored, 4 a block (128 B)
    CLIP_BEAVER_MOVEMENT_WATER         = 23,   //  4 frames, 4 stored, 3 a block (168 B)
    CLIP_BEAVER_MOVEMENT_WATER_WITH_STICK = 24,   //  4 frames, 4 stored, 2 a block (184 B)
    CLIP_BEAVER_DIVE                   = 25,   //  4 frames, 4 stored, 4 a block (128 B)
    CLIP_BEAVER_ASCENT                 = 26,   //  4 frames, 4 stored, 4 a block (116 B)
    CLIP_CHAMELEON_IDLE                = 27,   //  8 frames, 4 stored, 3 a block (168 B)
    CLIP_CHAMELEON_MOVEMENT            = 28,   //  8 frames, 8 stored, 3 a block (168 B)
    CLIP_CHAMELEON_TONGUE              = 29,   //  8 frames, 6 stored, 1 a block (272 B)
    CLIP_CHAMELEON_DAMAGE              = 30,   //  5 frames, 4 stored, 3 a block (168 B)
    CLIP_CHAMELEON_DEATH               = 31,   //  5 frames, 4 stored, 3 a block (168 B)
    CLIP_NEST_RACCOON                  = 32,   //  3 frames, 3 stored, 1 a block (440 B)
    CLIP_NEST_TURTLE                   = 33,   //  3 frames, 3 stored, 1 a block (440 B)
    CLIP_NEST_BEAVER                   = 34,   //  3 frames, 3 stored, 1 a block (488 B)
    CLIP_NEST_CHAMELEON                = 35,   //  3 frames, 3 stored, 1 a block (472 B)
    CLIP_MUSH_RED                      = 36,   //  2 frames, 2 stored, 5 a block (96 B)
    CLIP_MUSH_WHITE                    = 37,   //  2 frames, 2 stored, 4 a block (104 B)
    CLIP_SPAWN_PUFF                    = 38,   //  4 frames, 4 stored, 2 a block (176 B)
    CLIP_STICK_SPIN                    = 39,   //  8 frames, 8 stored, 5 a block (96 B)
    CLIP_GATE_PART                     = 40,   //  4 frames, 4 stored, 1 a block (488 B)
    CLIP_SWIPE_ARC                     = 41,   //  1 frames, 1 stored, 2 a block (200 B)
    CLIP_COUNT = 42
};

enum : uint8_t {
    SHEET_SQUIRE     = 0,
    SHEET_RACCOON    = 1,
    SHEET_TURTLE     = 2,
    SHEET_BEAVER     = 3,
    SHEET_CHAMELEON  = 4,
    SHEET_NEST       = 5,
    SHEET_MUSH       = 6,
    SHEET_SPAWN      = 7,
    SHEET_STICK      = 8,
    SHEET_GATE       = 9,
    SHEET_SWIPE      = 10,
    SHEET_COUNT = 11
};

extern const BankClip BANK_CLIPS[CLIP_COUNT];
extern const uint8_t BANK_FMAP[];
extern const uint8_t BANK_FSIZE[];    // a stored frame's bytes / 4 (header included)
extern const uint8_t BANK_SHEET_CLIP[SHEET_COUNT + 1];   // a sheet's first clip; [SHEET_COUNT] = CLIP_COUNT
extern const char *const BANK_CLIP_NAME[CLIP_COUNT];   // "RACCOON RUN" (the sprite lab)

// Stored frame of played frame f.
inline uint8_t bankStored(const BankClip &c, uint8_t f) {
    return c.map == BANK_NO_MAP ? f : BANK_FMAP[c.map + f];
}

// Stored frames a block (not a field of the table: 2 B a clip less, M8d).
inline uint32_t bankPerBlock(const BankClip &c) { return 128u / c.slot4; }

// Bytes of stored frame s, header included.
inline uint32_t bankSize(const BankClip &c, uint32_t s) { return BANK_FSIZE[c.sizes + s] * 4u; }

// 60 Hz ticks a frame is shown (its ms, rounded; at least 1).
inline uint32_t bankTicks(const BankClip &c) {
    uint32_t n = (c.msPer10 * 3u + 2) / 5;
    return n ? n : 1;
}
