// GENERATED by tools/assets/packbank.py (tools/mkcard.py runs it). Do not edit:
// re-run it.
#include "Bank.h"

const BankClip BANK_CLIPS[CLIP_COUNT] = {
    {   0,  4,  44, 16, 0xFF,  4, 0x00,   0},   // CLIP_SQUIRE_IDLE
    {   2,  8,  59,  9, 0xFF,  8, 0x00,   4},   // CLIP_SQUIRE_WALK
    {   6,  7,  86,  5, 0xFF,  7, 0x45,  12},   // CLIP_SQUIRE_THRUST
    {  13,  6,  65,  5, 0xFF,  6, 0x00,  19},   // CLIP_SQUIRE_PARRY
    {  19,  4,  62,  8, 0xFF,  4, 0x00,  25},   // CLIP_SQUIRE_DAMAGE
    {  21,  5,  62, 12, 0xFF,  5, 0x00,  29},   // CLIP_SQUIRE_DEATH
    {  24,  8,  38, 10, 0x00,  6, 0x00,  34},   // CLIP_RACCOON_IDLE
    {  26,  8,  41, 10, 0xFF,  8, 0x00,  40},   // CLIP_RACCOON_RUN
    {  29,  4,  44, 10, 0xFF,  4, 0x22,  48},   // CLIP_RACCOON_ATTACK
    {  31,  4,  38, 10, 0x08,  3, 0x00,  52},   // CLIP_RACCOON_DEATH
    {  32, 12,  44, 10, 0x0C,  6, 0x00,  55},   // CLIP_TURTLE_IDLE_YAWN
    {  35, 10,  38, 10, 0x18,  5, 0x00,  61},   // CLIP_TURTLE_IDLE_BLINK
    {  37,  4,  38, 10, 0x22,  3, 0x00,  66},   // CLIP_TURTLE_WALK
    {  38,  6,  42, 10, 0x26,  4, 0x00,  69},   // CLIP_TURTLE_SLEEP
    {  40,  5,  44, 10, 0xFF,  5, 0x23,  73},   // CLIP_TURTLE_BITE
    {  43, 10,  38, 10, 0x2C,  9, 0x00,  78},   // CLIP_TURTLE_SHELL
    {  46,  4,  32, 10, 0xFF,  4, 0x00,  87},   // CLIP_BEAVER_IDLE
    {  47,  4,  32, 10, 0xFF,  4, 0x00,  91},   // CLIP_BEAVER_MOVEMENT
    {  48,  4,  42, 10, 0xFF,  4, 0x00,  95},   // CLIP_BEAVER_MOVEMENT_WITH_STICK
    {  50,  4,  32, 10, 0xFF,  4, 0x22,  99},   // CLIP_BEAVER_BITE
    {  51,  4,  35, 10, 0xFF,  4, 0x00, 103},   // CLIP_BEAVER_DAMAGE
    {  53,  2, 114, 10, 0xFF,  2, 0x00, 107},   // CLIP_BEAVER_DEATH
    {  55,  4,  32, 10, 0xFF,  4, 0x00, 109},   // CLIP_BEAVER_IDLE_WATER
    {  56,  4,  42, 10, 0xFF,  4, 0x00, 113},   // CLIP_BEAVER_MOVEMENT_WATER
    {  58,  4,  46, 10, 0xFF,  4, 0x00, 117},   // CLIP_BEAVER_MOVEMENT_WATER_WITH_STICK
    {  60,  4,  32, 10, 0xFF,  4, 0x00, 121},   // CLIP_BEAVER_DIVE
    {  61,  4,  29, 10, 0xFF,  4, 0x00, 125},   // CLIP_BEAVER_ASCENT
    {  62,  8,  42, 10, 0x36,  4, 0x00, 129},   // CLIP_CHAMELEON_IDLE
    {  64,  8,  42, 10, 0xFF,  8, 0x00, 133},   // CLIP_CHAMELEON_MOVEMENT
    {  67,  8,  68, 10, 0x3E,  6, 0x24, 141},   // CLIP_CHAMELEON_TONGUE
    {  73,  5,  42, 10, 0x46,  4, 0x00, 147},   // CLIP_CHAMELEON_DAMAGE
    {  75,  5,  42, 10, 0x4B,  4, 0x00, 151},   // CLIP_CHAMELEON_DEATH
    {  77,  3, 110, 10, 0xFF,  3, 0x00, 155},   // CLIP_NEST_RACCOON
    {  80,  3, 110, 10, 0xFF,  3, 0x00, 158},   // CLIP_NEST_TURTLE
    {  83,  3, 122, 10, 0xFF,  3, 0x00, 161},   // CLIP_NEST_BEAVER
    {  86,  3, 118, 10, 0xFF,  3, 0x00, 164},   // CLIP_NEST_CHAMELEON
    {  89,  2,  24, 10, 0xFF,  2, 0x00, 167},   // CLIP_MUSH_RED
    {  90,  2,  26, 10, 0xFF,  2, 0x00, 169},   // CLIP_MUSH_WHITE
    {  91,  4,  44,  8, 0xFF,  4, 0x00, 171},   // CLIP_SPAWN_PUFF
    {  93,  8,  24,  5, 0xFF,  8, 0x00, 175},   // CLIP_STICK_SPIN
    {  95,  4, 122, 10, 0xFF,  4, 0x00, 183},   // CLIP_GATE_PART
    {  99,  1,  50,  5, 0xFF,  1, 0x00, 187},   // CLIP_SWIPE_ARC
};

const uint8_t BANK_FMAP[] = {
    0, 1, 2, 3, 4, 5, 0, 0,  // CLIP_RACCOON_IDLE
    0, 1, 2, 2,  // CLIP_RACCOON_DEATH
    0, 1, 2, 3, 4, 5, 5, 5, 4, 3, 0, 0,  // CLIP_TURTLE_IDLE_YAWN
    0, 1, 2, 3, 3, 2, 1, 4, 4, 4,  // CLIP_TURTLE_IDLE_BLINK
    0, 1, 0, 2,  // CLIP_TURTLE_WALK
    0, 1, 1, 1, 2, 3,  // CLIP_TURTLE_SLEEP
    0, 1, 2, 3, 4, 5, 6, 7, 8, 6,  // CLIP_TURTLE_SHELL
    0, 1, 1, 1, 2, 3, 3, 3,  // CLIP_CHAMELEON_IDLE
    0, 1, 2, 3, 4, 5, 1, 0,  // CLIP_CHAMELEON_TONGUE
    0, 1, 2, 3, 0,  // CLIP_CHAMELEON_DAMAGE
    0, 1, 2, 3, 3,  // CLIP_CHAMELEON_DEATH
};

const uint8_t BANK_FSIZE[] = {
    42, 42, 44, 42,  // CLIP_SQUIRE_IDLE
    42, 42, 38, 42, 40, 59, 56, 59,  // CLIP_SQUIRE_WALK
    65, 65, 65, 44, 86, 86, 86,  // CLIP_SQUIRE_THRUST
    65, 65, 65, 44, 65, 65,  // CLIP_SQUIRE_PARRY
    42, 62, 42, 42,  // CLIP_SQUIRE_DAMAGE
    42, 62, 53, 32, 38,  // CLIP_SQUIRE_DEATH
    38, 38, 38, 38, 38, 38,  // CLIP_RACCOON_IDLE
    38, 38, 35, 38, 38, 41, 38, 41,  // CLIP_RACCOON_RUN
    38, 44, 41, 32,  // CLIP_RACCOON_ATTACK
    38, 35, 29,  // CLIP_RACCOON_DEATH
    38, 35, 35, 38, 41, 44,  // CLIP_TURTLE_IDLE_YAWN
    38, 38, 38, 38, 38,  // CLIP_TURTLE_IDLE_BLINK
    38, 35, 35,  // CLIP_TURTLE_WALK
    42, 35, 42, 42,  // CLIP_TURTLE_SLEEP
    38, 41, 44, 41, 38,  // CLIP_TURTLE_BITE
    38, 35, 32, 18, 18, 18, 18, 20, 20,  // CLIP_TURTLE_SHELL
    32, 32, 32, 32,  // CLIP_BEAVER_IDLE
    32, 32, 32, 32,  // CLIP_BEAVER_MOVEMENT
    32, 42, 35, 35,  // CLIP_BEAVER_MOVEMENT_WITH_STICK
    32, 32, 32, 32,  // CLIP_BEAVER_BITE
    32, 35, 32, 29,  // CLIP_BEAVER_DAMAGE
    26, 114,  // CLIP_BEAVER_DEATH
    29, 32, 32, 29,  // CLIP_BEAVER_IDLE_WATER
    32, 42, 35, 32,  // CLIP_BEAVER_MOVEMENT_WATER
    42, 42, 46, 42,  // CLIP_BEAVER_MOVEMENT_WATER_WITH_STICK
    29, 32, 26, 14,  // CLIP_BEAVER_DIVE
    16, 18, 16, 29,  // CLIP_BEAVER_ASCENT
    42, 42, 38, 38,  // CLIP_CHAMELEON_IDLE
    38, 42, 42, 42, 38, 42, 42, 42,  // CLIP_CHAMELEON_MOVEMENT
    42, 46, 68, 68, 57, 46,  // CLIP_CHAMELEON_TONGUE
    42, 42, 38, 42,  // CLIP_CHAMELEON_DAMAGE
    42, 38, 34, 26,  // CLIP_CHAMELEON_DEATH
    110, 94, 66,  // CLIP_NEST_RACCOON
    110, 110, 102,  // CLIP_NEST_TURTLE
    122, 102, 77,  // CLIP_NEST_BEAVER
    118, 118, 74,  // CLIP_NEST_CHAMELEON
    24, 24,  // CLIP_MUSH_RED
    26, 26,  // CLIP_MUSH_WHITE
    20, 44, 44, 38,  // CLIP_SPAWN_PUFF
    14, 24, 15, 24, 14, 24, 15, 24,  // CLIP_STICK_SPIN
    122, 122, 122, 122,  // CLIP_GATE_PART
    50,  // CLIP_SWIPE_ARC
};

const uint8_t BANK_SHEET_CLIP[SHEET_COUNT + 1] = {0, 6, 10, 16, 27, 32, 36, 38, 39, 40, 41, 42};

const char *const BANK_CLIP_NAME[CLIP_COUNT] = {
    "SQUIRE IDLE",
    "SQUIRE WALK",
    "SQUIRE THRUST",
    "SQUIRE PARRY",
    "SQUIRE DAMAGE",
    "SQUIRE DEATH",
    "RACCOON IDLE",
    "RACCOON RUN",
    "RACCOON ATTACK",
    "RACCOON DEATH",
    "TURTLE IDLE YAWN",
    "TURTLE IDLE BLINK",
    "TURTLE WALK",
    "TURTLE SLEEP",
    "TURTLE BITE",
    "TURTLE SHELL",
    "BEAVER IDLE",
    "BEAVER MOVEMENT",
    "BEAVER MOVEMENT WITH STICK",
    "BEAVER BITE",
    "BEAVER DAMAGE",
    "BEAVER DEATH",
    "BEAVER IDLE WATER",
    "BEAVER MOVEMENT WATER",
    "BEAVER MOVEMENT WATER WITH STICK",
    "BEAVER DIVE",
    "BEAVER ASCENT",
    "CHAMELEON IDLE",
    "CHAMELEON MOVEMENT",
    "CHAMELEON TONGUE",
    "CHAMELEON DAMAGE",
    "CHAMELEON DEATH",
    "NEST RACCOON",
    "NEST TURTLE",
    "NEST BEAVER",
    "NEST CHAMELEON",
    "MUSH RED",
    "MUSH WHITE",
    "SPAWN PUFF",
    "STICK SPIN",
    "GATE PART",
    "SWIPE ARC",
};
