// GENERATED by tools/assets/bosspack.py (tools/mkcard.py runs it). Do not edit:
// re-run it.
//
// The giant toad on the card (section TOAD of CRITTERS.DAT), streamed every
// drawn frame and blitted from the landing buffer block by block
// (src/game/Boss.cpp). A frame is h rows of wWords words (gfx_blit4k's
// format, 15 transparent) in row bands: 128 / wWords whole rows a block, from
// its first block; ox, oy put its top-left relative to the toad's position
// (the middle of its feet line). Played frames that are the same picture
// share their blocks.
#pragma once
#include <stdint.h>

struct ToadFrame { uint8_t block, wWords, h; int8_t ox, oy; };

constexpr uint16_t TOAD_RED = 113;         // 30 pictures for 44 played frames; each again in red
                                         // (the hit flash) this many blocks on
constexpr uint8_t TOAD_MAX_BLOCKS = 6;    // the most a frame takes

// Each row's first played frame, and its length.
enum : uint8_t {
    TOAD_IDLE    =  0,  TOAD_IDLE_N    = 8,
    TOAD_BLINK   =  8,  TOAD_BLINK_N   = 8,
    TOAD_HOP     = 16,  TOAD_HOP_N     = 8,
    TOAD_TONGUE  = 24,  TOAD_TONGUE_N  = 8,
    TOAD_HURT    = 32,  TOAD_HURT_N    = 4,
    TOAD_DEATH   = 36,  TOAD_DEATH_N   = 8,
    TOAD_FRAMES = 44
};

extern const ToadFrame TOAD_FRAME[TOAD_FRAMES];

// Whole rows a block of frame f holds.
inline uint32_t toadRows(const ToadFrame &f) { return 128u / f.wWords; }
