// GENERATED by tools/assets/bosspack.py (tools/mkcard.py runs it). Do not edit:
// re-run it.
#include "Boss.h"

const ToadFrame TOAD_FRAME[TOAD_FRAMES] = {
    {  0,  8, 50, -28, -49},   // TOAD_IDLE 0: 4 blocks
    {  4,  8, 50, -28, -49},   // TOAD_IDLE 1: 4 blocks
    {  8,  8, 50, -28, -49},   // TOAD_IDLE 2: 4 blocks
    { 12,  8, 50, -28, -49},   // TOAD_IDLE 3: 4 blocks
    { 16,  8, 50, -28, -49},   // TOAD_IDLE 4: 4 blocks
    { 12,  8, 50, -28, -49},   // TOAD_IDLE 5: 4 blocks
    {  8,  8, 50, -28, -49},   // TOAD_IDLE 6: 4 blocks
    {  4,  8, 50, -28, -49},   // TOAD_IDLE 7: 4 blocks
    {  0,  8, 50, -28, -49},   // TOAD_BLINK 0: 4 blocks
    { 20,  8, 50, -28, -49},   // TOAD_BLINK 1: 4 blocks
    { 24,  8, 50, -28, -49},   // TOAD_BLINK 2: 4 blocks
    { 28,  8, 50, -28, -49},   // TOAD_BLINK 3: 4 blocks
    { 32,  8, 50, -28, -49},   // TOAD_BLINK 4: 4 blocks
    { 28,  8, 50, -28, -49},   // TOAD_BLINK 5: 4 blocks
    { 24,  8, 50, -28, -49},   // TOAD_BLINK 6: 4 blocks
    { 20,  8, 50, -28, -49},   // TOAD_BLINK 7: 4 blocks
    {  0,  8, 50, -28, -49},   // TOAD_HOP 0: 4 blocks
    { 36,  7, 56, -28, -55},   // TOAD_HOP 1: 4 blocks
    { 40, 11, 57, -47, -60},   // TOAD_HOP 2: 6 blocks
    { 46, 11, 43, -41, -57},   // TOAD_HOP 3: 4 blocks
    { 50,  8, 43, -24, -48},   // TOAD_HOP 4: 3 blocks
    { 53,  8, 47, -21, -45},   // TOAD_HOP 5: 3 blocks
    { 56,  8, 50, -26, -49},   // TOAD_HOP 6: 4 blocks
    {  0,  8, 50, -28, -49},   // TOAD_HOP 7: 4 blocks
    {  0,  8, 50, -28, -49},   // TOAD_TONGUE 0: 4 blocks
    { 60,  8, 50, -28, -49},   // TOAD_TONGUE 1: 4 blocks
    { 64,  8, 48, -28, -47},   // TOAD_TONGUE 2: 3 blocks
    { 67,  9, 50, -28, -49},   // TOAD_TONGUE 3: 4 blocks
    { 71,  8, 53, -28, -52},   // TOAD_TONGUE 4: 4 blocks
    { 75,  8, 50, -28, -49},   // TOAD_TONGUE 5: 4 blocks
    { 79,  8, 50, -28, -49},   // TOAD_TONGUE 6: 4 blocks
    { 83,  8, 50, -28, -49},   // TOAD_TONGUE 7: 4 blocks
    {  0,  8, 50, -28, -49},   // TOAD_HURT 0: 4 blocks
    { 87,  8, 49, -28, -48},   // TOAD_HURT 1: 4 blocks
    { 91,  8, 48, -28, -47},   // TOAD_HURT 2: 3 blocks
    { 94,  8, 49, -28, -48},   // TOAD_HURT 3: 4 blocks
    {  0,  8, 50, -28, -49},   // TOAD_DEATH 0: 4 blocks
    { 87,  8, 49, -28, -48},   // TOAD_DEATH 1: 4 blocks
    { 98,  8, 48, -28, -47},   // TOAD_DEATH 2: 3 blocks
    {101,  8, 45, -28, -44},   // TOAD_DEATH 3: 3 blocks
    {104,  8, 44, -28, -43},   // TOAD_DEATH 4: 3 blocks
    {107,  8, 42, -28, -41},   // TOAD_DEATH 5: 3 blocks
    {110,  8, 41, -28, -40},   // TOAD_DEATH 6: 3 blocks
    {110,  8, 41, -28, -40},   // TOAD_DEATH 7: 3 blocks
};
