// GENERATED by tools/mkcard.py (tools/card/cardfile.py). Do not edit: re-run it.
//
// The card file CRITTERS.DAT this build was made with: block 0's build hash
// and format (the game refuses any other card: WRONG CARD DATA), and each
// section's first block and length in 512 B blocks of the file.
#pragma once
#include <stdint.h>

constexpr uint16_t CARD_FORMAT = 1;
constexpr uint32_t CARD_HASH = 0x64EFDB04u;
constexpr uint32_t CARD_BLOCKS = 86711u;
constexpr uint32_t CARD_TITL_FIRST = 1u, CARD_TITL_BLOCKS = 257u;
constexpr uint32_t CARD_BANK_FIRST = 258u, CARD_BANK_BLOCKS = 100u;
constexpr uint32_t CARD_WRLD_FIRST = 358u, CARD_WRLD_BLOCKS = 83969u;
constexpr uint32_t CARD_OCCL_FIRST = 84327u, CARD_OCCL_BLOCKS = 1595u;
constexpr uint32_t CARD_TOAD_FIRST = 85922u, CARD_TOAD_BLOCKS = 226u;
constexpr uint32_t CARD_DEAD_FIRST = 86148u, CARD_DEAD_BLOCKS = 225u;
constexpr uint32_t CARD_WINC_FIRST = 86373u, CARD_WINC_BLOCKS = 321u;
constexpr uint32_t CARD_PMAP_FIRST = 86694u, CARD_PMAP_BLOCKS = 17u;
