// GENERATED by tools/assets/quantise.py --header from tools/assets/palette.py.
// Do not edit: change palette.py and re-run.
//
// The game's sixteen colours in RGB444 (0xRGB, pal::init()'s format; the
// panel runs at 12 bpp, so these are exactly what it shows). Index 0 is the
// outline; 15 is the swamp water in the world and the transparent key in
// sprites (no sprite pixel uses it).
#pragma once
#include <stdint.h>

extern const uint16_t PALETTE[16];

enum : uint8_t {
    C_SOOT      =  0,   // 0x221 soot
    C_UMBER     =  1,   // 0x532 umber
    C_PEAT      =  2,   // 0x854 peat
    C_BARK      =  3,   // 0xB75 bark
    C_MUD       =  4,   // 0xFD9 mud
    C_BONE      =  5,   // 0xFFD bone
    C_DEEPMOSS  =  6,   // 0x342 deepmoss
    C_BOG       =  7,   // 0x563 bog
    C_MOSS      =  8,   // 0x8A4 moss
    C_LICHEN    =  9,   // 0xCE6 lichen
    C_OCHRE     = 10,   // 0xFB4 ochre
    C_FOG       = 11,   // 0xCEE fog
    C_SLATE     = 12,   // 0x666 slate
    C_STONE     = 13,   // 0xBBA stone
    C_RUST      = 14,   // 0xE43 rust
    C_WATER     = 15,   // 0x467 swampwater
    C_OUTLINE   = C_SOOT,
    C_KEY       = C_WATER,   // sprites: transparent
};

// Colour -> colour tables for gfx_blit4k's GFX_B4_REMAP, gfx_remapRect() and
// gfx_sprite4(), made from the colours by palette.py (15, the sprite key,
// stays 15 except in REMAP_DARK, REMAP_LIGHT and REMAP_SEPIA, which also shade
// the water).
extern const uint8_t REMAP_RED[16];    // the hit flash: a red ramp by lightness, the shading kept
extern const uint8_t REMAP_WHITE[16];  // every opaque colour to bone: a white flash
extern const uint8_t REMAP_DARK[16];   // each colour a step darker: shadows on the ground (gfx_remapRect)
extern const uint8_t REMAP_LIGHT[16];  // each colour a step lighter: highlights, glints
extern const uint8_t REMAP_ROT[16];    // swamp rot: greys and mouldy greens, the red kept (corrupted critters)
extern const uint8_t REMAP_SEPIA[16];  // the pause map's fog: the parchment's browns by lightness, the water too
