// GENERATED by tools/assets/quantise.py --header from tools/assets/palette.py.
// Do not edit: change palette.py and re-run.
#include "Palette.h"

const uint16_t PALETTE[16] = {
    0x221,  //  0 soot
    0x532,  //  1 umber
    0x854,  //  2 peat
    0xB75,  //  3 bark
    0xFD9,  //  4 mud
    0xFFD,  //  5 bone
    0x342,  //  6 deepmoss
    0x563,  //  7 bog
    0x8A4,  //  8 moss
    0xCE6,  //  9 lichen
    0xFB4,  // 10 ochre
    0xCEE,  // 11 fog
    0x666,  // 12 slate
    0xBBA,  // 13 stone
    0xE43,  // 14 rust
    0x467,  // 15 swampwater
};

// REMAP_RED: the hit flash: a red ramp by lightness, the shading kept
// bark>rust mud>rust deep>umbe bog>peat moss>rust lich>rust ochr>rust fog>rust slat>peat ston>rust
const uint8_t REMAP_RED[16] = {0, 1, 2, 14, 14, 5, 1, 2, 14, 14, 14, 14, 2, 14, 14, 15};

// REMAP_WHITE: every opaque colour to bone: a white flash
// soot>bone umbe>bone peat>bone bark>bone mud>bone deep>bone bog>bone moss>bone lich>bone ochr>bone fog>bone slat>bone ston>bone rust>bone
const uint8_t REMAP_WHITE[16] = {5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 15};

// REMAP_DARK: each colour a step darker: shadows on the ground (gfx_remapRect)
// umbe>soot peat>umbe bark>peat mud>bark bone>ston deep>soot bog>deep moss>bog lich>moss ochr>bark fog>ston slat>soot ston>slat rust>peat swam>soot
const uint8_t REMAP_DARK[16] = {0, 0, 1, 2, 3, 13, 0, 6, 7, 8, 3, 13, 0, 12, 2, 0};

// REMAP_LIGHT: each colour a step lighter: highlights, glints
// soot>slat umbe>peat peat>bark bark>mud mud>bone deep>bog bog>moss moss>lich lich>bone ochr>mud fog>bone slat>ston ston>bone rust>ochr swam>ston
const uint8_t REMAP_LIGHT[16] = {12, 2, 3, 4, 5, 5, 7, 8, 9, 5, 4, 5, 13, 5, 10, 13};

// REMAP_ROT: swamp rot: greys and mouldy greens, the red kept (corrupted critters)
// umbe>deep peat>bog bark>slat mud>fog bone>fog moss>ston lich>fog ochr>ston slat>bog
const uint8_t REMAP_ROT[16] = {0, 6, 7, 12, 11, 11, 6, 7, 13, 11, 13, 11, 7, 13, 14, 15};

// REMAP_SEPIA: the pause map's fog: the parchment's browns by lightness, the water too
// soot>peat umbe>peat peat>bark bone>mud deep>peat bog>bark moss>bark lich>mud ochr>mud fog>mud slat>bark ston>mud rust>bark swam>bark
const uint8_t REMAP_SEPIA[16] = {2, 2, 3, 3, 4, 4, 2, 3, 3, 4, 4, 4, 3, 4, 3, 3};
