// GENERATED by tools/world/paint.py from tools/world/map.txt and objects.json.
// Do not edit: change those and re-run it (tools/mkcard.py does).
//
// The world the card's WRLD section holds (tools/world/worldpack.py has the
// layout) and what the game needs to know about it without the card: the
// terrain under every 8 px cell, the regions, where the squire starts, the
// nests and mushrooms, the gate to The Rot and the arena behind it. World
// pixels throughout.
#pragma once
#include <stdint.h>

constexpr int16_t WORLD_W = 1024, WORLD_H = 768;
// Card layout: NC column blocks a band, NB bands (every 8 rows, 128 tall),
// TPH ambient phases (the whole world painted once for each: reeds
// swaying, ripples, glints, lily pads, gnats), LAYERS world layers (0 the
// swamp, 1 healed: The Rot as it is once its toad is beaten).
constexpr uint16_t WORLD_NC = 128, WORLD_NB = 82;
constexpr uint8_t WORLD_TPH = 4, WORLD_LAYERS = 2;

// Terrain, a class a cell, run-length coded row by row: a run is a byte,
// the class in its low 2 bits and its length - 1 in the high 6 (runs over
// 64 cells are split; a row's runs add up to TERRAIN_W), and TERRAIN_ROW[y]
// is the index of row y's first run (src/engine/Terrain.cpp walks them).
constexpr uint8_t TERRAIN_CELL = 8, TERRAIN_W = 128, TERRAIN_H = 96;
enum : uint8_t { T_OPEN, T_SHALLOW, T_DEEP, T_SOLID };
constexpr uint16_t TERRAIN_RUN_COUNT = 1145;
extern const uint8_t TERRAIN_RUNS[TERRAIN_RUN_COUNT];
extern const uint16_t TERRAIN_ROW[TERRAIN_H];
#ifdef CHTEST
// The same flat, 2 bits a cell, 4 a byte (the leftmost in the low bits), for
// the host tests to check the runs against (never in the game).
extern const uint8_t TERRAIN_FLAT[TERRAIN_W / 4 * TERRAIN_H];
#endif

struct WorldRect { int16_t x0, y0, x1, y1; };          // [x0, x1) x [y0, y1)
struct WorldRegion { WorldRect r; uint8_t name; };     // the first that holds a point
struct WorldSpot { int16_t x, y; uint8_t kind; };

constexpr uint8_t REGION_NAMES = 5, REGION_RECTS = 6;
enum : uint8_t { R_ROT, R_WILLOW_HOLLOW, R_REED_SHALLOWS, R_LANDING, R_BEAVER_DAM };
extern const char *const REGION_NAME[REGION_NAMES];
extern const WorldRegion REGIONS[REGION_RECTS];

constexpr int16_t START_X = 160, START_Y = 626;       // the squire's feet
constexpr WorldRect GATE = {752, 288, 800, 336};        // into The Rot: open terrain, the game shuts it
// The arena, The Rot's pond: where the toad may land; the squire's feet in
// ARENA_TRIGGER start the fight; the toad rises at TOAD_X, TOAD_Y; its rot
// raccoons come out of the reeds at ARENA_REEDS.
constexpr WorldRect ARENA = {688, 40, 992, 288};
constexpr WorldRect ARENA_TRIGGER = {696, 48, 984, 256};
constexpr int16_t TOAD_X = 840, TOAD_Y = 204;
constexpr uint8_t ARENA_REED_COUNT = 4;
constexpr int16_t ARENA_REEDS[ARENA_REED_COUNT][2] = {{796, 134}, {944, 200}, {816, 200}, {880, 206}};

enum : uint8_t { NEST_RACCOON, NEST_TURTLE, NEST_BEAVER, NEST_CHAMELEON };
constexpr uint8_t NEST_COUNT = 6;
extern const WorldSpot NESTS[NEST_COUNT];

// Pickups: A2/A3 red (heal a little), B2/B3 white (heal a lot).
// Each is x | y << 10 | kind << 20 (4 bytes, not a WorldSpot's 6).
enum : uint8_t { MUSH_A2, MUSH_A3, MUSH_B2, MUSH_B3 };
constexpr uint8_t MUSHROOM_COUNT = 48;
extern const uint32_t MUSHROOMS[MUSHROOM_COUNT];
inline int16_t mushX(uint32_t m) { return (int16_t)(m & 1023); }
inline int16_t mushY(uint32_t m) { return (int16_t)((m >> 10) & 1023); }
inline uint8_t mushKind(uint32_t m) { return (uint8_t)(m >> 20); }

// Occluders: the willows an actor can get behind (tools/world/occlpack.py;
// src/engine/Occluders.h redraws them over him). A tree's shape (its sheet
// and flip): its rectangle, wWords words x h rows, the trunk's foot (ax, ay)
// in it, whose row is the base line (feet above it: behind the tree), and
// how its rows lie in the card's OCCL section (rowsPerBlock whole rows a
// block, `blocks` blocks from a fresh one).
struct OccluderShape { uint8_t wWords, h, ax, ay, rowsPerBlock, blocks; };
constexpr uint8_t OCCL_SHAPES = 10;
extern const OccluderShape OCCL_SHAPE[OCCL_SHAPES];
// The trees by base y, then x, 3 bytes each (little-endian): foot x | (base y
// & 63) << 10 | shape << 16 | shown << 20, base y's band the one it is listed
// in, shown how much of its rectangle it shows (0-15; the rest is covered by
// trees in front of it); their rows in the same order in OCCL after its header.
constexpr uint16_t OCCL_COUNT = 163;
extern const uint8_t OCCLUDERS[OCCL_COUNT * 3];
// Every 1 << OCCL_BAND_SHIFT rows of base y: the first tree with its base there
// or below and that tree's first block (after the header); [OCCL_BANDS]: the end.
constexpr uint8_t OCCL_BAND_SHIFT = 6, OCCL_BANDS = 12;
// The most rows a tree reaches above its base line, and below it.
constexpr uint8_t OCCL_ABOVE = 85, OCCL_BELOW = 2;
struct OccluderBand { uint16_t first, block; };
extern const OccluderBand OCCL_BAND[OCCL_BANDS + 1];
// Each world layer has its own copy of the trees' rows (the same pixels in
// its colours: The Rot's willows dead in layer 0, alive in 1), OCCL_LAYER_BLOCKS
// blocks each, layer 0's first.
constexpr uint16_t OCCL_LAYER_BLOCKS = 797;

