"""Ethan's Critters: the card file CRITTERS.DAT (a generic writer and reader).

The game reads its art from one file in the card's root, as raw 512 B card
blocks through the file's FAT runs (CHSd), so everything here is in whole
blocks and every section starts on a block boundary: a section is one
contiguous range of blocks, and a read of it is one CMD18 (two where the
file's runs split).

Block 0, the header (little-endian; every field naturally aligned, so the
game reads them as words straight from its 4-aligned landing buffer):

    0   char  magic[8]      "ECRTCARD"
    8   u16   version       FORMAT (1)
    10  u16   sections      how many table entries are used (<= 16)
    12  u32   build hash    CRC32 over the used table entries (16 B each, as
                            stored) followed by every section's padded
                            content, in table order
    16  u32   total blocks  the header and every section
    20  entry table[16]     {char tag[4]; u32 first block; u32 blocks;
                            u32 crc32 of the section's padded content}
    276 zero to the end of the block

The build hash is also compiled into the game (src/assets/CardIndex.h, made
by emit_index()), so a card from another build is told apart at boot
("WRONG CARD DATA") and the game never needs to CRC anything itself.

Output is deterministic: the same sections give the same bytes.
"""
import re
import struct
import zlib
from pathlib import Path

BLOCK = 512
MAGIC = b"ECRTCARD"
FORMAT = 1
MAX_SECTIONS = 16
HEADER = struct.Struct("<8sHHII")       # magic, version, sections, build hash, total blocks
ENTRY = struct.Struct("<4sIII")         # tag, first block, blocks, crc32
TABLE = HEADER.size                     # 20: the entry table's offset in block 0
TAG = re.compile(r"^[A-Z0-9]{4}$")


class CardError(ValueError):
    """A card file that is not what it says it is."""


def crc32(data):
    return zlib.crc32(data) & 0xFFFFFFFF


def blocks_of(nbytes):
    return (nbytes + BLOCK - 1) // BLOCK


def pad(data):
    """data padded with zeros to whole blocks (at least one)."""
    n = max(1, blocks_of(len(data)))
    return bytes(data) + bytes(n * BLOCK - len(data))


class Section:
    def __init__(self, tag, data, first):
        self.tag = tag
        self.data = pad(data)           # padded: what is on the card
        self.size = len(data)           # before padding
        self.first = first
        self.blocks = len(self.data) // BLOCK
        self.crc = crc32(self.data)

    def entry(self):
        return ENTRY.pack(self.tag.encode("ascii"), self.first, self.blocks, self.crc)

    def __repr__(self):
        return "Section(%r, first=%d, blocks=%d, crc=%08x)" % (self.tag, self.first, self.blocks, self.crc)


class CardFile:
    def __init__(self):
        self.sections = []

    # --- building -------------------------------------------------------------

    def add_section(self, tag, data):
        """Appends a section (padded to whole blocks) and returns it."""
        if not TAG.match(tag):
            raise CardError("section tag %r: four capitals or digits" % tag)
        if any(s.tag == tag for s in self.sections):
            raise CardError("section %r twice" % tag)
        if len(self.sections) >= MAX_SECTIONS:
            raise CardError("more than %d sections" % MAX_SECTIONS)
        s = Section(tag, data, self.total_blocks)
        self.sections.append(s)
        return s

    def section(self, tag):
        for s in self.sections:
            if s.tag == tag:
                return s
        raise KeyError(tag)

    @property
    def total_blocks(self):
        return 1 + sum(s.blocks for s in self.sections)

    @property
    def build_hash(self):
        h = zlib.crc32(b"".join(s.entry() for s in self.sections))
        for s in self.sections:
            h = zlib.crc32(s.data, h)
        return h & 0xFFFFFFFF

    def header(self):
        b = bytearray(BLOCK)
        HEADER.pack_into(b, 0, MAGIC, FORMAT, len(self.sections), self.build_hash, self.total_blocks)
        for i, s in enumerate(self.sections):
            b[TABLE + i * ENTRY.size:TABLE + (i + 1) * ENTRY.size] = s.entry()
        return bytes(b)

    def to_bytes(self):
        return self.header() + b"".join(s.data for s in self.sections)

    def write(self, path):
        """Writes the card file; returns its bytes."""
        data = self.to_bytes()
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
        return data

    def index_text(self, generator="tools/mkcard.py"):
        """src/assets/CardIndex.h: what the game checks the card against, and
        where each section starts."""
        L = [
            "// GENERATED by %s (tools/card/cardfile.py). Do not edit: re-run it." % generator,
            "//",
            "// The card file CRITTERS.DAT this build was made with: block 0's build hash",
            "// and format (the game refuses any other card: WRONG CARD DATA), and each",
            "// section's first block and length in 512 B blocks of the file.",
            "#pragma once",
            "#include <stdint.h>",
            "",
            "constexpr uint16_t CARD_FORMAT = %d;" % FORMAT,
            "constexpr uint32_t CARD_HASH = 0x%08Xu;" % self.build_hash,
            "constexpr uint32_t CARD_BLOCKS = %du;" % self.total_blocks,
        ]
        for s in self.sections:
            L.append("constexpr uint32_t CARD_%s_FIRST = %du, CARD_%s_BLOCKS = %du;"
                     % (s.tag, s.first, s.tag, s.blocks))
        return "\n".join(L) + "\n"

    def emit_index(self, header_path, generator="tools/mkcard.py"):
        """Writes the header, only if it changed (no needless rebuilds).
        Returns True when it was written."""
        text = self.index_text(generator)
        p = Path(header_path)
        if p.exists() and p.read_text(encoding="utf-8") == text:
            return False
        p.parent.mkdir(parents=True, exist_ok=True)
        with open(p, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
        return True


# --- reading (tests, tools) ----------------------------------------------------

def parse(data):
    """A CardFile from a card file's bytes, every check the game makes and
    more (each section's CRC). Raises CardError."""
    data = bytes(data)
    if len(data) < BLOCK or len(data) % BLOCK:
        raise CardError("%d bytes: not whole blocks" % len(data))
    magic, version, count, bhash, total = HEADER.unpack_from(data, 0)
    if magic != MAGIC:
        raise CardError("magic %r" % magic)
    if version != FORMAT:
        raise CardError("format %d, this reader knows %d" % (version, FORMAT))
    if count > MAX_SECTIONS:
        raise CardError("%d sections" % count)
    if total * BLOCK != len(data):
        raise CardError("header says %d blocks, the file has %d" % (total, len(data) // BLOCK))
    if any(data[TABLE + count * ENTRY.size:BLOCK]):
        raise CardError("junk after the section table")
    card = CardFile()
    nxt = 1
    for i in range(count):
        tag, first, blocks, crc = ENTRY.unpack_from(data, TABLE + i * ENTRY.size)
        tag = tag.decode("ascii", "replace")
        if first != nxt or blocks < 1:
            raise CardError("section %s at block %d (+%d), expected at %d" % (tag, first, blocks, nxt))
        body = data[first * BLOCK:(first + blocks) * BLOCK]
        s = card.add_section(tag, body)
        if s.crc != crc:
            raise CardError("section %s: crc %08x, the table says %08x" % (tag, s.crc, crc))
        nxt = first + blocks
    if nxt != total:
        raise CardError("sections end at block %d, the header says %d" % (nxt, total))
    if card.build_hash != bhash:
        raise CardError("build hash %08x, the header says %08x" % (card.build_hash, bhash))
    return card


def read(path):
    return parse(Path(path).read_bytes())
